# Syndicate Operative Outfit - Civilian
- type: startingGear
  id: NanotrasenOperativeGearCivilian
  equipment:
    jumpsuit: ClothingUniformJumpsuitNTFormal
    back: ClothingBackpackDuffelNanotrasen
    shoes: ClothingShoesBootsJack
    gloves: ClothingHandsGlovesColorBlack
    id: NTPDA
    ears: ClothingHeadsetAltNanotrasen

# Nanotrasen Footsoldier Gear - No Headset
- type: startingGear
  id: NanotrasenFootsoldierGearRuin
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperativeNT
    head: ClothingHeadHelmetSwatNanotrasen
    mask: ClothingMaskGasNanotrasen
    outerClothing: ClothingOuterArmorBasic
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpack
    shoes: ClothingShoesBootsJack
    id: NTPDA
  storage:
    back:
    - BoxSurvival

# Syndicate Footsoldier Gear
- type: startingGear
  id: NanotrasenFootsoldierGear
  parent: NanotrasenOperativeGearCivilian
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperativeNT
    head: ClothingHeadHelmetSwatNanotrasen
    eyes: ClothingEyesHudNanotrasen
    outerClothing: ClothingOuterArmorBasic
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpack
    shoes: ClothingShoesBootsJackFilled
  storage:
    back:
    - BoxSurvivalNanotrasen

- type: startingGear
  id: NanotrasenFootsoldierTeamLeaderGear
  parent: NanotrasenFootsoldierGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNTFormal
    head: ClothingHeadHatOutlawHat
    outerClothing: ClothingOuterArmorBasicSlim
    back: ClothingBackpackSatchel
    pocket1: BaseUplinkRadio25TCNT
    pocket2: EnergySword

# Pet Gear
- type: startingGear
  id: MobMonkeyGearCold
  equipment:
    head: ClothingHeadHatCanadaBeanie
    ears: ClothingHeadsetService
    jumpsuit: ClothingUniformJumpsuitJacketMonkey
    outerClothing: ClothingOuterWinterBar
    id: PunPunIDCard

- type: startingGear
  id: MobMimeletGear
  equipment:
    mask: ClothingMaskMime

# InterDyne Pharmaceuticals gear
- type: startingGear
  id: InterdyneBiodroneGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitGenetics
    eyes: ClothingEyesGlassesSurplusBallisticInterdyne
    outerClothing: ClothingOuterCoatHighCollar
    gloves: ClothingHandsGlovesNitrile
    shoes: ClothingShoesBootsJack
    pocket1: LauncherSyringe
  inhand:
  - CombatScalpel

# Five Points Armory gear
- type: startingGear
  id: FPAHenchmanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNanotrasen
    head: ClothingHeadHatBluesoft
    eyes: ClothingEyesGlassesCheapSunglassesBig
    outerClothing: ClothingCorpoJacketFPA
    gloves: ClothingHandsGlovesFingerless
    id: NTPDA
    ears: ClothingHeadsetAltNanotrasen
    shoes: ClothingShoesBootsNTFilled
    pocket1: WeaponLaserSvalinn
    pocket2: PowerCellHigh
  inhand:
  - TelescopicBaton

- type: startingGear
  id: FPACaptainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCaptain
    head: ClothingHeadHatCapcap
    outerClothing: ClothingCorpoJacketFPA
    id: NTPDA
    ears: ClothingHeadsetAltNanotrasen
    belt: ClothingBeltSheathFilled
    shoes: ClothingShoesBootsNTFilled
    pocket1: PowerCellHigh
  inhand:
  - WeaponEnergyShotgun
